/**
 * Canonical StockSense demo dataset.
 *
 * The Steel Rods narrative is the spine of the demo and is deliberately left at
 * zero so the evaluator can walk it end to end:
 *
 *   RC-1001 receive 100 kg  →  Central Warehouse 100
 *   TR-2001 transfer 100 kg →  Central 0 · Production Rack 100 · total 100
 *   DL-3001 deliver 20 kg   →  Production Rack 80 · total 80
 *   count 77, book 80       →  ADJ-4001 difference −3
 *   ADJ-4001 posted         →  Production Rack 77 · total 77
 *
 * Everything else in the dataset is generated by replaying a movement history
 * through `HistoryBuilder`, so the stock map, the ledger running balance and the
 * document list can never disagree. The builder fails loudly at boot if a
 * movement would drive a leaf below zero.
 */
import type {
  Adjustment,
  Category,
  Count,
  Database,
  Delivery,
  LedgerEntry,
  LedgerType,
  Location,
  Product,
  Receipt,
  ReorderRule,
  Transfer,
  Uom,
  User,
  Warehouse,
} from './types.js';
import { hashPassword } from './crypto.js';

export const SEED_VERSION = 5;

const TODAY = '2026-09-26';

/** Local line-id generator so seeding never has to reach into the live store. */
let seedLineSeq = 1;
function lineId(prefix: string): string {
  return `${prefix}-${String(seedLineSeq++).padStart(4, '0')}`;
}

/* ------------------------------------------------------------------ people */

const USERS: User[] = [
  {
    id: 'U-1001',
    name: 'Rahul Sharma',
    email: 'demo@stocksense.app',
    role: 'Inventory Manager',
    title: 'Inventory Manager',
    initials: 'RS',
    employeeCode: 'SS-1041',
    active: true,
    lastActiveAt: '2026-09-26T08:41',
  },
  {
    id: 'U-1002',
    name: 'Priya Patel',
    email: 'priya@stocksense.app',
    role: 'Warehouse Staff',
    title: 'Warehouse Associate · Central',
    initials: 'PP',
    employeeCode: 'SS-1078',
    active: true,
    lastActiveAt: '2026-09-26T08:12',
  },
  {
    id: 'U-1003',
    name: 'Sana Kapoor',
    email: 'admin@stocksense.app',
    role: 'Admin',
    title: 'Systems Administrator',
    initials: 'SK',
    employeeCode: 'SS-1002',
    active: true,
    lastActiveAt: '2026-09-25T19:02',
  },
  {
    id: 'U-1004',
    name: 'Vikram Iyer',
    email: 'viewer@stocksense.app',
    role: 'Viewer',
    title: 'Finance Analyst · Read only',
    initials: 'VI',
    employeeCode: 'SS-1220',
    active: true,
    lastActiveAt: '2026-09-24T16:35',
  },
];

const PASSWORDS: Record<string, string> = {
  'U-1001': 'Demo@1234',
  'U-1002': 'Demo@1234',
  'U-1003': 'Admin@1234',
  'U-1004': 'Demo@1234',
};

/* -------------------------------------------------------------- structure */

const CATEGORIES: Category[] = [
  { id: 'CAT-01', name: 'Raw Materials', icon: 'iron' },
  { id: 'CAT-02', name: 'Computer Hardware', icon: 'memory' },
  { id: 'CAT-03', name: 'Electronics', icon: 'devices' },
  { id: 'CAT-04', name: 'Furniture', icon: 'chair' },
  { id: 'CAT-05', name: 'Networking', icon: 'lan' },
  { id: 'CAT-06', name: 'Packaging', icon: 'label' },
];

const WAREHOUSES: Warehouse[] = [
  {
    code: 'WH-CEN',
    name: 'Central Warehouse',
    kind: 'Central',
    address: 'Survey 118, Logistics Park Road, Industrial Estate Phase II',
    manager: 'Rahul Sharma',
    capacityUnits: 1400,
  },
  {
    code: 'WH-PRD',
    name: 'Production Floor',
    kind: 'Production',
    address: 'Unit 7, Plant Wing, Industrial Estate Phase II',
    manager: 'Arjun Menon',
    capacityUnits: 600,
  },
  {
    code: 'WH-DSP',
    name: 'Dispatch Bay',
    kind: 'Dispatch',
    address: 'Gate 3, Logistics Park Road, Industrial Estate Phase II',
    manager: 'Priya Patel',
    capacityUnits: 320,
  },
  {
    code: 'WH-SEC',
    name: 'Secondary Warehouse',
    kind: 'Secondary',
    address: 'Plot 22, Overflow Yard, Logistics Park Road',
    manager: 'Neha Kulkarni',
    capacityUnits: 500,
  },
];

const LOCATIONS: Location[] = [
  {
    code: 'WH-CEN',
    name: 'Central Warehouse',
    warehouse: 'WH-CEN',
    container: true,
    type: 'Storage',
    capacityUnits: 0,
    volumePerUnit: 0,
    state: 'Active',
  },
  {
    code: 'WH-CEN/Receiving',
    name: 'Receiving',
    warehouse: 'WH-CEN',
    parent: 'WH-CEN',
    container: false,
    type: 'Receiving',
    capacityUnits: 120,
    volumePerUnit: 0.02,
    state: 'Receiving',
  },
  {
    code: 'WH-CEN/Main-Storage',
    name: 'Main Storage',
    warehouse: 'WH-CEN',
    parent: 'WH-CEN',
    container: true,
    type: 'Storage',
    capacityUnits: 1100,
    volumePerUnit: 0,
    state: 'Active',
  },
  {
    code: 'WH-CEN/Main-Storage/Heavy-Rack-A',
    name: 'Heavy Rack A',
    warehouse: 'WH-CEN',
    parent: 'WH-CEN/Main-Storage',
    container: false,
    type: 'Heavy Rack',
    capacityUnits: 500,
    volumePerUnit: 0.05,
    state: 'Active',
  },
  {
    code: 'WH-CEN/Main-Storage/Rack-B',
    name: 'Rack B',
    warehouse: 'WH-CEN',
    parent: 'WH-CEN/Main-Storage',
    container: false,
    type: 'Storage',
    capacityUnits: 320,
    volumePerUnit: 0.01,
    state: 'Active',
  },
  {
    code: 'WH-CEN/Main-Storage/Bay-04',
    name: 'Bay 04',
    warehouse: 'WH-CEN',
    parent: 'WH-CEN/Main-Storage',
    container: false,
    type: 'Storage',
    capacityUnits: 280,
    volumePerUnit: 0.008,
    state: 'Active',
  },
  {
    code: 'WH-PRD',
    name: 'Production Floor',
    warehouse: 'WH-PRD',
    container: true,
    type: 'Storage',
    capacityUnits: 0,
    volumePerUnit: 0,
    state: 'Active',
  },
  {
    code: 'WH-PRD/Production-Rack',
    name: 'Production Rack',
    warehouse: 'WH-PRD',
    parent: 'WH-PRD',
    container: false,
    type: 'Storage',
    capacityUnits: 320,
    volumePerUnit: 0.05,
    state: 'Active',
  },
  {
    code: 'WH-PRD/Assembly-Area',
    name: 'Assembly Area',
    warehouse: 'WH-PRD',
    parent: 'WH-PRD',
    container: false,
    type: 'Assembly',
    capacityUnits: 280,
    volumePerUnit: 0.01,
    state: 'Active',
  },
  {
    code: 'WH-DSP',
    name: 'Dispatch Bay',
    warehouse: 'WH-DSP',
    container: true,
    type: 'Storage',
    capacityUnits: 0,
    volumePerUnit: 0,
    state: 'Dispatch',
  },
  {
    code: 'WH-DSP/Packing-Area',
    name: 'Packing Area',
    warehouse: 'WH-DSP',
    parent: 'WH-DSP',
    container: false,
    type: 'Packing',
    capacityUnits: 160,
    volumePerUnit: 0.006,
    state: 'Packing',
  },
  {
    code: 'WH-DSP/Ready-to-Ship',
    name: 'Ready to Ship',
    warehouse: 'WH-DSP',
    parent: 'WH-DSP',
    container: false,
    type: 'Dispatch',
    capacityUnits: 160,
    volumePerUnit: 0.01,
    state: 'Dispatch',
  },
  {
    code: 'WH-SEC',
    name: 'Secondary Warehouse',
    warehouse: 'WH-SEC',
    container: true,
    type: 'Storage',
    capacityUnits: 0,
    volumePerUnit: 0,
    state: 'Active',
  },
  {
    code: 'WH-SEC/Main-Storage',
    name: 'Main Storage',
    warehouse: 'WH-SEC',
    parent: 'WH-SEC',
    container: false,
    type: 'Storage',
    capacityUnits: 500,
    volumePerUnit: 0.01,
    state: 'Active',
  },
];

/* --------------------------------------------------------------- catalogue */

function reorder(
  productSku: string,
  minStock: number,
  reorderPoint: number,
  safetyStock: number,
  reorderQty: number,
  preferredSupplier: string,
  leadTimeDays: number,
): ReorderRule {
  return { productSku, minStock, reorderPoint, safetyStock, reorderQty, preferredSupplier, leadTimeDays };
}

interface ProductSeed {
  id: string;
  name: string;
  sku: string;
  barcode: string;
  category: string;
  uom: Uom;
  unitCost: number;
  icon: string;
  reorder: ReorderRule;
  createdAt: string;
  updatedAt: string;
}

const PRODUCT_SEEDS: ProductSeed[] = [
  {
    id: 'PRD-1001',
    name: 'Steel Rods 12mm High Tensile',
    sku: 'STL-ROD-12',
    barcode: '8901248001927',
    category: 'Raw Materials',
    uom: 'kg',
    unitCost: 95,
    icon: 'iron',
    reorder: reorder('STL-ROD-12', 40, 120, 60, 500, 'Apex Metallurgical Ltd', 5),
    createdAt: '2025-11-02',
    updatedAt: '2026-09-18',
  },
  {
    id: 'PRD-1002',
    name: 'Samsung SSD 1TB',
    sku: 'SSD-SAM-1TB',
    barcode: '8806092991184',
    category: 'Computer Hardware',
    uom: 'Units',
    unitCost: 8500,
    icon: 'memory',
    reorder: reorder('SSD-SAM-1TB', 12, 20, 8, 25, 'Meridian Tech Distribution', 7),
    createdAt: '2025-11-02',
    updatedAt: '2026-09-12',
  },
  {
    id: 'PRD-1003',
    name: 'Kingston DDR4 RAM 16GB',
    sku: 'RAM-KNG-16',
    barcode: '0742533912665',
    category: 'Computer Hardware',
    uom: 'Units',
    unitCost: 3200,
    icon: 'developer_board',
    reorder: reorder('RAM-KNG-16', 10, 15, 6, 30, 'Meridian Tech Distribution', 6),
    createdAt: '2025-11-02',
    updatedAt: '2026-09-15',
  },
  {
    id: 'PRD-1004',
    name: 'Dell 24" Monitor',
    sku: 'MON-DEL-24',
    barcode: '5397184684629',
    category: 'Computer Hardware',
    uom: 'Units',
    unitCost: 18500,
    icon: 'monitor',
    reorder: reorder('MON-DEL-24', 3, 6, 2, 10, 'Brightwave Display Systems', 12),
    createdAt: '2025-11-04',
    updatedAt: '2026-09-20',
  },
  {
    id: 'PRD-1005',
    name: 'Industrial Barcode Scanner',
    sku: 'SCN-IND-2D',
    barcode: '4710781983211',
    category: 'Electronics',
    uom: 'Units',
    unitCost: 11500,
    icon: 'qr_code_scanner',
    reorder: reorder('SCN-IND-2D', 6, 10, 4, 20, 'Vega Scanning Systems', 9),
    createdAt: '2025-11-04',
    updatedAt: '2026-09-17',
  },
  {
    id: 'PRD-1006',
    name: 'Ergonomic Office Chair',
    sku: 'CHR-ERG-01',
    barcode: '8904352110098',
    category: 'Furniture',
    uom: 'Units',
    unitCost: 9800,
    icon: 'chair',
    reorder: reorder('CHR-ERG-01', 5, 8, 3, 15, 'Meridian Furnishings', 14),
    createdAt: '2025-11-06',
    updatedAt: '2026-09-10',
  },
  {
    id: 'PRD-1007',
    name: 'Wireless Mouse',
    sku: 'MOU-WLS-01',
    barcode: '5099887766113',
    category: 'Electronics',
    uom: 'Units',
    unitCost: 850,
    icon: 'mouse',
    reorder: reorder('MOU-WLS-01', 12, 20, 8, 40, 'Vega Scanning Systems', 8),
    createdAt: '2025-11-06',
    updatedAt: '2026-09-23',
  },
  {
    id: 'PRD-1008',
    name: 'Cat6 Cable',
    sku: 'CAB-CAT6-01',
    barcode: '4006381333931',
    category: 'Networking',
    uom: 'Rolls',
    unitCost: 2200,
    icon: 'cable',
    reorder: reorder('CAB-CAT6-01', 3, 5, 2, 10, 'Netlink Cable Works', 10),
    createdAt: '2025-11-08',
    updatedAt: '2026-09-22',
  },
  {
    id: 'PRD-1009',
    name: 'Thermal Labels',
    sku: 'LBL-406-01',
    barcode: '8906029094416',
    category: 'Packaging',
    uom: 'Rolls',
    unitCost: 320,
    icon: 'sell',
    reorder: reorder('LBL-406-01', 8, 12, 5, 30, 'Printline Packaging', 4),
    createdAt: '2025-11-08',
    updatedAt: '2026-09-21',
  },
  {
    id: 'PRD-1010',
    name: 'Copper Conduit',
    sku: 'COP-50M-01',
    barcode: '8905563001284',
    category: 'Raw Materials',
    uom: 'Rolls',
    unitCost: 3400,
    icon: 'cable',
    reorder: reorder('COP-50M-01', 4, 6, 2, 12, 'Copperline Industries', 11),
    createdAt: '2025-11-10',
    updatedAt: '2026-09-14',
  },
];

/* ------------------------------------------------------- history generator */

interface MoveSpec {
  at: string;
  type: Extract<LedgerType, 'OPENING' | 'RECEIPT' | 'DELIVERY' | 'TRANSFER' | 'ADJUSTMENT'>;
  ref: string;
  qty: number;
  /** Receipts and adjustments land here. */
  to?: string;
  /** Deliveries and transfers leave from here. */
  from?: string;
  /** Transfers only. */
  toMove?: string;
  user: string;
  note: string;
}

class HistoryBuilder {
  private balances = new Map<string, Map<string, number>>();
  readonly ledger: LedgerEntry[] = [];
  private n = 0;

  constructor(private products: Map<string, Product>) {}

  private leaves(sku: string): Map<string, number> {
    let m = this.balances.get(sku);
    if (!m) {
      m = new Map();
      this.balances.set(sku, m);
    }
    return m;
  }

  private apply(sku: string, location: string, delta: number): void {
    const m = this.leaves(sku);
    const next = Math.round(((m.get(location) ?? 0) + delta) * 1e6) / 1e6;
    if (next < 0) {
      throw new Error(
        `Seed history error: ${sku} would fall to ${next} at ${location}. Reduce the movement quantity.`,
      );
    }
    m.set(location, next);
  }

  private total(sku: string): number {
    let sum = 0;
    for (const v of this.leaves(sku).values()) sum += v;
    return Math.round(sum * 1e6) / 1e6;
  }

  run(sku: string, steps: MoveSpec[]): void {
    const product = this.products.get(sku);
    if (!product) throw new Error(`Seed history error: unknown SKU ${sku}`);

    for (const step of steps) {
      const legs: { location: string; delta: number }[] = [];
      let delta = 0;

      if (step.type === 'OPENING') {
        const target = step.to as string;
        delta = step.qty;
        this.apply(sku, target, delta);
        legs.push({ location: target, delta });
      } else if (step.type === 'RECEIPT') {
        delta = step.qty;
        this.apply(sku, step.to as string, delta);
        legs.push({ location: step.to as string, delta });
      } else if (step.type === 'DELIVERY') {
        delta = -step.qty;
        this.apply(sku, step.from as string, delta);
        legs.push({ location: step.from as string, delta });
      } else if (step.type === 'TRANSFER') {
        this.apply(sku, step.from as string, -step.qty);
        this.apply(sku, step.toMove as string, step.qty);
        legs.push({ location: step.from as string, delta: -step.qty });
        legs.push({ location: step.toMove as string, delta: step.qty });
      } else {
        delta = step.qty;
        this.apply(sku, step.to as string, delta);
        legs.push({ location: step.to as string, delta });
      }

      const balanceAfter = this.total(sku);
      this.ledger.push({
        id: `LG-${String(++this.n).padStart(5, '0')}`,
        at: step.at,
        type: step.type,
        ref: step.ref,
        sku,
        name: product.name,
        delta,
        from: step.from ?? (step.type === 'RECEIPT' ? 'Supplier' : '—'),
        to: step.toMove ?? step.to ?? '—',
        legs,
        balanceAfter,
        user: step.user,
        note: step.note,
      });
    }

    // Write the replayed position back onto the product.
    const map: Record<string, number> = {};
    for (const [loc, value] of this.leaves(sku)) {
      if (value > 0) map[loc] = value;
    }
    product.stock = map;
    product.updatedAt = steps[steps.length - 1]?.at.slice(0, 10) ?? product.updatedAt;
  }
}

const HISTORY: Record<string, MoveSpec[]> = {
  'SSD-SAM-1TB': [
    { at: '2026-08-03T08:30', type: 'OPENING', ref: 'OPEN-2026', qty: 40, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-04T10:20', type: 'RECEIPT', ref: 'RC-1008', qty: 20, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Rahul Sharma', note: 'Goods received against PO-2026-4410.' },
    { at: '2026-08-19T15:40', type: 'DELIVERY', ref: 'DL-3008', qty: 4, from: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Dispatch completed, proof of delivery captured.' },
    { at: '2026-08-28T11:05', type: 'DELIVERY', ref: 'DL-3009', qty: 6, from: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Dispatch completed for Bluewave Retail.' },
    { at: '2026-09-02T11:10', type: 'TRANSFER', ref: 'TR-2006', qty: 6, from: 'WH-CEN/Main-Storage/Rack-B', toMove: 'WH-SEC/Main-Storage', user: 'Priya Patel', note: 'Relocation to the overflow yard — enterprise balance unchanged.' },
    { at: '2026-09-12T09:30', type: 'ADJUSTMENT', ref: 'ADJ-4005', qty: 1, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Arjun Menon', note: 'Counting Error — one unit found in an unlabelled carton.' },
  ],
  'RAM-KNG-16': [
    { at: '2026-08-03T08:32', type: 'OPENING', ref: 'OPEN-2026', qty: 30, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-11T13:15', type: 'RECEIPT', ref: 'RC-1010', qty: 24, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Goods received against PO-2026-4462.' },
    { at: '2026-08-27T16:20', type: 'DELIVERY', ref: 'DL-3010', qty: 8, from: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Dispatch completed, proof of delivery captured.' },
    { at: '2026-09-04T09:45', type: 'TRANSFER', ref: 'TR-2007', qty: 8, from: 'WH-CEN/Main-Storage/Rack-B', toMove: 'WH-PRD/Assembly-Area', user: 'Priya Patel', note: 'Kitted to the assembly line.' },
    { at: '2026-09-15T14:00', type: 'DELIVERY', ref: 'DL-3011', qty: 4, from: 'WH-PRD/Assembly-Area', user: 'Arjun Menon', note: 'Scrap module returned to dispatch after rebuild.' },
  ],
  'MON-DEL-24': [
    { at: '2026-08-03T08:34', type: 'OPENING', ref: 'OPEN-2026', qty: 7, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-21T12:30', type: 'DELIVERY', ref: 'DL-3012', qty: 2, from: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Dispatch completed for Pixel Print House.' },
    { at: '2026-09-08T10:10', type: 'RECEIPT', ref: 'RC-1011', qty: 6, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Goods received against PO-2026-4501.' },
    { at: '2026-09-18T17:05', type: 'DELIVERY', ref: 'DL-3006', qty: 6, from: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Dispatch completed, proof of delivery captured.' },
    { at: '2026-09-20T08:50', type: 'TRANSFER', ref: 'TR-2008', qty: 1, from: 'WH-CEN/Main-Storage/Bay-04', toMove: 'WH-DSP/Ready-to-Ship', user: 'Priya Patel', note: 'Staged on the outbound dock for tomorrow.' },
  ],
  'SCN-IND-2D': [
    { at: '2026-08-03T08:36', type: 'OPENING', ref: 'OPEN-2026', qty: 5, to: 'WH-SEC/Main-Storage', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-14T11:45', type: 'RECEIPT', ref: 'RC-1012', qty: 12, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Goods received against PO-2026-4520.' },
    { at: '2026-09-01T14:10', type: 'DELIVERY', ref: 'DL-3007', qty: 5, from: 'WH-SEC/Main-Storage', user: 'Priya Patel', note: 'Dispatch completed for Kaveri Traders.' },
    { at: '2026-09-09T10:20', type: 'TRANSFER', ref: 'TR-2009', qty: 3, from: 'WH-CEN/Main-Storage/Rack-B', toMove: 'WH-SEC/Main-Storage', user: 'Priya Patel', note: 'Topped up the overflow yard ahead of a service visit.' },
    { at: '2026-09-17T16:45', type: 'ADJUSTMENT', ref: 'ADJ-4006', qty: 1, to: 'WH-SEC/Main-Storage', user: 'Arjun Menon', note: 'Supplier surplus found during a spot check.' },
  ],
  'CHR-ERG-01': [
    { at: '2026-08-03T08:38', type: 'OPENING', ref: 'OPEN-2026', qty: 12, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-17T09:30', type: 'RECEIPT', ref: 'RC-1013', qty: 16, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Goods received against PO-2026-4535.' },
    { at: '2026-08-29T13:55', type: 'DELIVERY', ref: 'DL-3013', qty: 5, from: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Dispatch completed for Meridian Furnishings.' },
    { at: '2026-09-10T15:20', type: 'ADJUSTMENT', ref: 'ADJ-4003', qty: -1, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Damaged — one chair frame cracked in transit, scrapped.' },
    { at: '2026-09-17T11:00', type: 'TRANSFER', ref: 'TR-2010', qty: 2, from: 'WH-CEN/Main-Storage/Bay-04', toMove: 'WH-DSP/Ready-to-Ship', user: 'Priya Patel', note: 'Staged on the outbound dock.' },
  ],
  'MOU-WLS-01': [
    { at: '2026-08-03T08:38', type: 'OPENING', ref: 'OPEN-2026', qty: 40, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-03T08:40', type: 'OPENING', ref: 'OPEN-2026', qty: 8, to: 'WH-PRD/Assembly-Area', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-07T10:15', type: 'RECEIPT', ref: 'RC-1005', qty: 24, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Goods received against PO-2026-4388.' },
    { at: '2026-09-05T16:35', type: 'DELIVERY', ref: 'DL-3004', qty: 20, from: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Dispatch completed, proof of delivery captured.' },
    { at: '2026-09-11T09:40', type: 'TRANSFER', ref: 'TR-2011', qty: 12, from: 'WH-CEN/Main-Storage/Bay-04', toMove: 'WH-PRD/Assembly-Area', user: 'Priya Patel', note: 'Consumables moved to the assembly line.' },
    { at: '2026-09-19T17:10', type: 'DELIVERY', ref: 'DL-3014', qty: 6, from: 'WH-PRD/Assembly-Area', user: 'Arjun Menon', note: 'Dispatch completed for Northline Services.' },
    { at: '2026-09-23T09:25', type: 'ADJUSTMENT', ref: 'ADJ-4007', qty: 2, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Arjun Menon', note: 'Counting Error — two units found behind a racking beam.' },
  ],
  'CAB-CAT6-01': [
    { at: '2026-08-03T08:42', type: 'OPENING', ref: 'OPEN-2026', qty: 4, to: 'WH-SEC/Main-Storage', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-13T14:05', type: 'RECEIPT', ref: 'RC-1014', qty: 6, to: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Goods received against PO-2026-4561.' },
    { at: '2026-09-03T11:30', type: 'DELIVERY', ref: 'DL-3015', qty: 3, from: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Dispatch completed for Lumen Projects.' },
    { at: '2026-09-08T15:15', type: 'TRANSFER', ref: 'TR-2012', qty: 2, from: 'WH-CEN/Main-Storage/Rack-B', toMove: 'WH-SEC/Main-Storage', user: 'Priya Patel', note: 'Relocation to the overflow yard.' },
    { at: '2026-09-16T10:50', type: 'ADJUSTMENT', ref: 'ADJ-4008', qty: -2, to: 'WH-SEC/Main-Storage', user: 'Arjun Menon', note: 'Damaged — outer wrap torn and water ingressed on two reels.' },
    { at: '2026-09-22T08:35', type: 'TRANSFER', ref: 'TR-2013', qty: 1, from: 'WH-SEC/Main-Storage', toMove: 'WH-CEN/Main-Storage/Rack-B', user: 'Priya Patel', note: 'Pulled back to the main rack for an urgent order.' },
  ],
  'LBL-406-01': [
    { at: '2026-08-03T08:44', type: 'OPENING', ref: 'OPEN-2026', qty: 20, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-06T09:20', type: 'RECEIPT', ref: 'RC-1006', qty: 30, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Goods received against PO-2026-4370.' },
    { at: '2026-08-24T13:40', type: 'DELIVERY', ref: 'DL-3016', qty: 18, from: 'WH-CEN/Main-Storage/Bay-04', user: 'Priya Patel', note: 'Dispatch completed for Printline Packaging.' },
    { at: '2026-09-01T16:00', type: 'ADJUSTMENT', ref: 'ADJ-4009', qty: -5, to: 'WH-CEN/Main-Storage/Bay-04', user: 'Rahul Sharma', note: 'Missing — five reels unaccounted for at the monthly count. Investigation opened.' },
    { at: '2026-09-12T08:45', type: 'TRANSFER', ref: 'TR-2014', qty: 4, from: 'WH-CEN/Main-Storage/Bay-04', toMove: 'WH-DSP/Packing-Area', user: 'Priya Patel', note: 'Moved to the packing bench for the weekly run.' },
    { at: '2026-09-15T10:10', type: 'RECEIPT', ref: 'RC-1015', qty: 10, to: 'WH-DSP/Packing-Area', user: 'Priya Patel', note: 'Short delivery from Printline booked straight into packing.' },
    { at: '2026-09-21T17:25', type: 'DELIVERY', ref: 'DL-3017', qty: 8, from: 'WH-DSP/Packing-Area', user: 'Priya Patel', note: 'Dispatch completed for Pixel Print House.' },
  ],
  'COP-50M-01': [
    { at: '2026-08-03T08:46', type: 'OPENING', ref: 'OPEN-2026', qty: 9, to: 'WH-CEN/Main-Storage/Heavy-Rack-A', user: 'Rahul Sharma', note: 'Opening position carried forward at the start of the financial year.' },
    { at: '2026-08-10T11:30', type: 'RECEIPT', ref: 'RC-1016', qty: 12, to: 'WH-CEN/Main-Storage/Heavy-Rack-A', user: 'Priya Patel', note: 'Goods received against PO-2026-4590.' },
    { at: '2026-08-26T15:00', type: 'DELIVERY', ref: 'DL-3018', qty: 4, from: 'WH-CEN/Main-Storage/Heavy-Rack-A', user: 'Priya Patel', note: 'Dispatch completed for Kaveri Traders.' },
    { at: '2026-09-01T09:20', type: 'TRANSFER', ref: 'TR-2004', qty: 2, from: 'WH-CEN/Main-Storage/Heavy-Rack-A', toMove: 'WH-SEC/Main-Storage', user: 'Priya Patel', note: 'Relocation to the overflow yard.' },
    { at: '2026-09-14T11:40', type: 'ADJUSTMENT', ref: 'ADJ-4010', qty: -1, to: 'WH-CEN/Main-Storage/Heavy-Rack-A', user: 'Arjun Menon', note: 'Expired — one reel past its shelf life, quarantined and written off.' },
  ],
};

/* ------------------------------------------------------------- documents */

function lines(
  items: { sku: string; expected?: number; received: number; bin: string; lot?: string }[],
) {
  return items.map((i, idx) => ({
    id: lineId('RL'),
    sku: i.sku,
    expected: i.expected ?? i.received,
    received: i.received,
    bin: i.bin,
    lot: i.lot ?? `LOT-26${String(idx + 1).padStart(2, '0')}`,
    barcode: '',
  }));
}

function dl(items: { sku: string; qty: number; bin: string; picked?: number; packed?: boolean }[]) {
  return items.map((i) => ({
    id: lineId('DL'),
    sku: i.sku,
    qty: i.qty,
    picked: i.picked ?? i.qty,
    bin: i.bin,
    packed: i.packed ?? true,
  }));
}

function tl(items: { sku: string; qty: number }[]) {
  return items.map((i) => ({ id: lineId('TL'), sku: i.sku, qty: i.qty }));
}

const RECEIPTS: Receipt[] = [
  // ---- open: the demo spine
  {
    ref: 'RC-1001',
    supplier: 'Apex Metallurgical Ltd',
    poRef: 'PO-2026-4612',
    bolRef: 'BOL-77410',
    contact: 'Nikhil Rao',
    destination: 'WH-CEN',
    scheduledDate: '2026-09-27',
    carrier: 'SwiftTrans Logistics',
    dockBay: 'Dock 02',
    status: 'Draft',
    lines: lines([
      { sku: 'STL-ROD-12', expected: 100, received: 0, bin: 'WH-CEN/Receiving', lot: 'HT-26-0912' },
    ]),
    notes: '12 mm high-tensile rod for the assembly week. Awaiting weighbridge ticket.',
    createdAt: '2026-09-25T16:10',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'RC-1002',
    supplier: 'Vega Scanning Systems',
    poRef: 'PO-2026-4618',
    bolRef: 'BOL-77426',
    contact: 'Ritu Malhotra',
    destination: 'WH-CEN',
    scheduledDate: '2026-09-26',
    carrier: 'DHL Freight',
    dockBay: 'Dock 01',
    status: 'Ready',
    lines: lines([{ sku: 'SCN-IND-2D', expected: 20, received: 0, bin: 'WH-CEN/Receiving' }]),
    notes: 'Vehicle at the gate. Count and serialise against the packing list.',
    createdAt: '2026-09-24T10:05',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'RC-1003',
    supplier: 'Netlink Cable Works',
    poRef: 'PO-2026-4620',
    bolRef: '—',
    contact: 'Arun Pillai',
    destination: 'WH-CEN',
    scheduledDate: '2026-09-28',
    carrier: 'Internal Shuttle',
    dockBay: 'Unassigned',
    status: 'Waiting',
    lines: lines([{ sku: 'CAB-CAT6-01', expected: 6, received: 0, bin: 'WH-CEN/Receiving' }]),
    notes: 'Supplier has not confirmed the dispatch date yet.',
    createdAt: '2026-09-24T12:40',
    createdBy: 'Priya Patel',
  },
  {
    ref: 'RC-1004',
    supplier: 'Copperline Industries',
    poRef: 'PO-2026-4624',
    bolRef: '—',
    contact: 'Deepak Rao',
    destination: 'WH-SEC',
    scheduledDate: '2026-09-30',
    carrier: 'Internal Shuttle',
    dockBay: 'Unassigned',
    status: 'Waiting',
    lines: lines([{ sku: 'COP-50M-01', expected: 8, received: 0, bin: 'WH-SEC/Main-Storage' }]),
    notes: 'Awaiting the mill test certificate before the dock is booked.',
    createdAt: '2026-09-25T09:15',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'RC-1007',
    supplier: 'Meridian Tech Distribution',
    poRef: 'PO-2026-4627',
    bolRef: '—',
    contact: 'Sara D’Souza',
    destination: 'WH-CEN',
    scheduledDate: '2026-10-02',
    carrier: '—',
    dockBay: 'Unassigned',
    status: 'Draft',
    lines: lines([{ sku: 'RAM-KNG-16', expected: 32, received: 0, bin: 'WH-CEN/Main-Storage/Rack-B' }]),
    notes: 'Drafted against the quarterly plan. PO not yet released.',
    createdAt: '2026-09-25T11:02',
    createdBy: 'Priya Patel',
  },
  {
    ref: 'RC-1009',
    supplier: 'Meridian Furnishings',
    poRef: 'PO-2026-4601',
    bolRef: 'BOL-77388',
    contact: 'Kunal Bose',
    destination: 'WH-CEN',
    scheduledDate: '2026-09-22',
    carrier: 'TCI Freight',
    dockBay: 'Dock 03',
    status: 'Canceled',
    lines: lines([{ sku: 'CHR-ERG-01', expected: 12, received: 0, bin: 'WH-CEN/Main-Storage/Bay-04' }]),
    notes: 'Duplicate of PO-2026-4601 raised in error. Purchase order withdrawn.',
    createdAt: '2026-09-21T14:30',
    createdBy: 'Rahul Sharma',
  },
  // ---- completed, referenced by the opening history
  {
    ref: 'RC-1005', supplier: 'Vega Scanning Systems', poRef: 'PO-2026-4388', bolRef: 'BOL-77012',
    contact: 'Ritu Malhotra', destination: 'WH-CEN', scheduledDate: '2026-08-07', carrier: 'DHL Freight',
    dockBay: 'Dock 01', status: 'Done',
    lines: lines([{ sku: 'MOU-WLS-01', expected: 24, received: 24, bin: 'WH-CEN/Main-Storage/Bay-04' }]),
    notes: 'Fully received, zero variance.', createdAt: '2026-08-06T08:40', createdBy: 'Priya Patel',
    validatedAt: '2026-08-07T10:15', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1006', supplier: 'Printline Packaging', poRef: 'PO-2026-4370', bolRef: 'BOL-76995',
    contact: 'Meera Joshi', destination: 'WH-CEN', scheduledDate: '2026-08-06', carrier: 'Internal Shuttle',
    dockBay: 'Dock 03', status: 'Done',
    lines: lines([{ sku: 'LBL-406-01', expected: 30, received: 30, bin: 'WH-CEN/Main-Storage/Bay-04' }]),
    notes: 'Thirty reels received and inspected.', createdAt: '2026-08-05T09:05', createdBy: 'Priya Patel',
    validatedAt: '2026-08-06T09:20', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1008', supplier: 'Meridian Tech Distribution', poRef: 'PO-2026-4410', bolRef: 'BOL-77140',
    contact: 'Sara D’Souza', destination: 'WH-CEN', scheduledDate: '2026-08-04', carrier: 'DHL Freight',
    dockBay: 'Dock 01', status: 'Done',
    lines: lines([{ sku: 'SSD-SAM-1TB', expected: 20, received: 20, bin: 'WH-CEN/Main-Storage/Rack-B' }]),
    notes: 'Serial numbers logged for all twenty drives.', createdAt: '2026-08-03T12:20', createdBy: 'Rahul Sharma',
    validatedAt: '2026-08-04T10:20', validatedBy: 'Rahul Sharma',
  },
  {
    ref: 'RC-1010', supplier: 'Meridian Tech Distribution', poRef: 'PO-2026-4462', bolRef: 'BOL-77260',
    contact: 'Sara D’Souza', destination: 'WH-CEN', scheduledDate: '2026-08-11', carrier: 'DHL Freight',
    dockBay: 'Dock 01', status: 'Done',
    lines: lines([{ sku: 'RAM-KNG-16', expected: 24, received: 24, bin: 'WH-CEN/Main-Storage/Rack-B' }]),
    notes: 'Full quantity received.', createdAt: '2026-08-10T16:00', createdBy: 'Priya Patel',
    validatedAt: '2026-08-11T13:15', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1011', supplier: 'Brightwave Display Systems', poRef: 'PO-2026-4501', bolRef: 'BOL-77340',
    contact: 'Tara Menon', destination: 'WH-CEN', scheduledDate: '2026-09-08', carrier: 'TCI Freight',
    dockBay: 'Dock 02', status: 'Done',
    lines: lines([{ sku: 'MON-DEL-24', expected: 6, received: 6, bin: 'WH-CEN/Main-Storage/Bay-04' }]),
    notes: 'Two cartons opened and checked, no damage.', createdAt: '2026-09-07T09:30', createdBy: 'Priya Patel',
    validatedAt: '2026-09-08T10:10', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1012', supplier: 'Vega Scanning Systems', poRef: 'PO-2026-4520', bolRef: 'BOL-77366',
    contact: 'Ritu Malhotra', destination: 'WH-CEN', scheduledDate: '2026-08-14', carrier: 'DHL Freight',
    dockBay: 'Dock 01', status: 'Done',
    lines: lines([{ sku: 'SCN-IND-2D', expected: 12, received: 12, bin: 'WH-CEN/Main-Storage/Rack-B' }]),
    notes: 'All twelve scanners paired to a handheld during receipt.', createdAt: '2026-08-13T15:45', createdBy: 'Priya Patel',
    validatedAt: '2026-08-14T11:45', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1013', supplier: 'Meridian Furnishings', poRef: 'PO-2026-4535', bolRef: 'BOL-77390',
    contact: 'Kunal Bose', destination: 'WH-CEN', scheduledDate: '2026-08-17', carrier: 'TCI Freight',
    dockBay: 'Dock 03', status: 'Done',
    lines: lines([{ sku: 'CHR-ERG-01', expected: 16, received: 16, bin: 'WH-CEN/Main-Storage/Bay-04' }]),
    notes: 'Sixteen chairs received and assembled check completed.', createdAt: '2026-08-16T10:10', createdBy: 'Priya Patel',
    validatedAt: '2026-08-17T09:30', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1014', supplier: 'Netlink Cable Works', poRef: 'PO-2026-4561', bolRef: 'BOL-77420',
    contact: 'Arun Pillai', destination: 'WH-CEN', scheduledDate: '2026-08-13', carrier: 'Internal Shuttle',
    dockBay: 'Dock 02', status: 'Done',
    lines: lines([{ sku: 'CAB-CAT6-01', expected: 6, received: 6, bin: 'WH-CEN/Main-Storage/Rack-B' }]),
    notes: 'Cat6 verified with a tester reel.', createdAt: '2026-08-12T11:20', createdBy: 'Priya Patel',
    validatedAt: '2026-08-13T14:05', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1015', supplier: 'Printline Packaging', poRef: 'PO-2026-4580', bolRef: 'BOL-77448',
    contact: 'Meera Joshi', destination: 'WH-DSP', scheduledDate: '2026-09-15', carrier: 'Internal Shuttle',
    dockBay: 'Pack Bench', status: 'Done',
    lines: lines([{ sku: 'LBL-406-01', expected: 12, received: 10, bin: 'WH-DSP/Packing-Area' }]),
    notes: 'Short by two reels — supplier credit raised.', createdAt: '2026-09-14T17:00', createdBy: 'Priya Patel',
    validatedAt: '2026-09-15T10:10', validatedBy: 'Priya Patel',
  },
  {
    ref: 'RC-1016', supplier: 'Copperline Industries', poRef: 'PO-2026-4590', bolRef: 'BOL-77462',
    contact: 'Deepak Rao', destination: 'WH-CEN', scheduledDate: '2026-08-10', carrier: 'TCI Freight',
    dockBay: 'Dock 02', status: 'Done',
    lines: lines([{ sku: 'COP-50M-01', expected: 12, received: 12, bin: 'WH-CEN/Main-Storage/Heavy-Rack-A' }]),
    notes: 'Twelve reels received with mill certificates.', createdAt: '2026-08-09T08:30', createdBy: 'Priya Patel',
    validatedAt: '2026-08-10T11:30', validatedBy: 'Priya Patel',
  },
];

const DELIVERIES: Delivery[] = [
  // ---- open: the demo spine (blocked until RC-1001 and TR-2001 run)
  {
    ref: 'DL-3001',
    customer: 'Laxmi Industrial Works',
    contact: 'Bhaskar Iyer',
    address: '14 Foundry Road, Phase II Industrial Estate',
    from: 'WH-PRD/Production-Rack',
    scheduledDate: '2026-09-26',
    carrier: 'BlueDart Express',
    status: 'Waiting',
    lines: dl([{ sku: 'STL-ROD-12', qty: 20, bin: 'WH-PRD/Production-Rack', picked: 0, packed: false }]),
    notes: 'Released against the fabrication order. Cannot be picked until rod stock is on the rack.',
    createdAt: '2026-09-25T10:20',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'DL-3002',
    customer: 'Nova Retail Systems',
    contact: 'Shalini Bose',
    address: 'Unit 9, Tech Park Block C',
    from: 'WH-CEN/Main-Storage/Rack-B',
    scheduledDate: '2026-09-26',
    carrier: 'DHL Express',
    status: 'Ready',
    lines: dl([
      { sku: 'SSD-SAM-1TB', qty: 4, bin: 'Rack B', picked: 0, packed: false },
      { sku: 'RAM-KNG-16', qty: 6, bin: 'Rack B', picked: 0, packed: false },
    ]),
    notes: 'Stock reserved. Awaiting release from the pick face.',
    createdAt: '2026-09-24T15:00',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'DL-3003',
    customer: 'Pixel Print House',
    contact: 'Aakash Verma',
    address: '7 Riverside Design Park',
    from: 'WH-DSP/Packing-Area',
    scheduledDate: '2026-09-26',
    carrier: 'Internal Shuttle',
    status: 'Picking',
    lines: dl([{ sku: 'LBL-406-01', qty: 4, bin: 'Packing Bench 2', picked: 2, packed: false }]),
    notes: 'Half picked. Waiting on the second bench to clear.',
    createdAt: '2026-09-25T13:45',
    createdBy: 'Priya Patel',
  },
  {
    ref: 'DL-3005',
    customer: 'Meridian Furnishings',
    contact: 'Kunal Bose',
    address: '22 Linking Road, South Extension',
    from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-09-29',
    carrier: 'Unassigned',
    status: 'Draft',
    lines: dl([{ sku: 'CHR-ERG-01', qty: 6, bin: 'Bay 04', picked: 0, packed: false }]),
    notes: 'Draft — not yet released to the floor.',
    createdAt: '2026-09-25T16:40',
    createdBy: 'Priya Patel',
  },
  // ---- completed, referenced by the opening history
  {
    ref: 'DL-3004', customer: 'Northline Services', contact: 'Ritika Bose',
    address: '3 Harbour Freight Terminals', from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-09-05', carrier: 'TCI Freight', status: 'Done',
    lines: dl([{ sku: 'MOU-WLS-01', qty: 20, bin: 'Bay 04' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-04T09:10', createdBy: 'Rahul Sharma',
    completedAt: '2026-09-05T16:35', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3006', customer: 'Bluewave Retail', contact: 'Sameer Gill',
    address: 'Unit 22, Tech Park Block C', from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-09-18', carrier: 'DHL Express', status: 'Done',
    lines: dl([{ sku: 'MON-DEL-24', qty: 6, bin: 'Bay 04' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-17T11:20', createdBy: 'Rahul Sharma',
    completedAt: '2026-09-18T17:05', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3007', customer: 'Kaveri Traders', contact: 'Naveen Iyer',
    address: '88 Sawmill Road', from: 'WH-SEC/Main-Storage',
    scheduledDate: '2026-09-01', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'SCN-IND-2D', qty: 5, bin: 'Overflow Rack' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-30T15:30', createdBy: 'Priya Patel',
    completedAt: '2026-09-01T14:10', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3008', customer: 'Corridor IT Services', contact: 'Farah Qureshi',
    address: '5 Cyber Park', from: 'WH-CEN/Main-Storage/Rack-B',
    scheduledDate: '2026-08-19', carrier: 'DHL Express', status: 'Done',
    lines: dl([{ sku: 'SSD-SAM-1TB', qty: 4, bin: 'Rack B' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-18T10:10', createdBy: 'Rahul Sharma',
    completedAt: '2026-08-19T15:40', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3009', customer: 'Bluewave Retail', contact: 'Sameer Gill',
    address: 'Unit 22, Tech Park Block C', from: 'WH-CEN/Main-Storage/Rack-B',
    scheduledDate: '2026-08-28', carrier: 'DHL Express', status: 'Done',
    lines: dl([{ sku: 'SSD-SAM-1TB', qty: 6, bin: 'Rack B' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-27T12:00', createdBy: 'Rahul Sharma',
    completedAt: '2026-08-28T11:05', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3010', customer: 'Corridor IT Services', contact: 'Farah Qureshi',
    address: '5 Cyber Park', from: 'WH-CEN/Main-Storage/Rack-B',
    scheduledDate: '2026-08-27', carrier: 'DHL Express', status: 'Done',
    lines: dl([{ sku: 'RAM-KNG-16', qty: 8, bin: 'Rack B' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-26T16:30', createdBy: 'Priya Patel',
    completedAt: '2026-08-27T16:20', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3011', customer: 'Kaveri Traders', contact: 'Naveen Iyer',
    address: '88 Sawmill Road', from: 'WH-PRD/Assembly-Area',
    scheduledDate: '2026-09-15', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'RAM-KNG-16', qty: 4, bin: 'Assembly Line 1' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-14T10:30', createdBy: 'Arjun Menon',
    completedAt: '2026-09-15T14:00', completedBy: 'Arjun Menon',
  },
  {
    ref: 'DL-3012', customer: 'Pixel Print House', contact: 'Aakash Verma',
    address: '7 Riverside Design Park', from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-08-21', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'MON-DEL-24', qty: 2, bin: 'Bay 04' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-20T11:15', createdBy: 'Priya Patel',
    completedAt: '2026-08-21T12:30', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3013', customer: 'Meridian Furnishings', contact: 'Kunal Bose',
    address: '22 Linking Road, South Extension', from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-08-29', carrier: 'TCI Freight', status: 'Done',
    lines: dl([{ sku: 'CHR-ERG-01', qty: 5, bin: 'Bay 04' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-28T14:00', createdBy: 'Priya Patel',
    completedAt: '2026-08-29T13:55', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3014', customer: 'Northline Services', contact: 'Ritika Bose',
    address: '3 Harbour Freight Terminals', from: 'WH-PRD/Assembly-Area',
    scheduledDate: '2026-09-19', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'MOU-WLS-01', qty: 6, bin: 'Assembly Line 1' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-18T15:45', createdBy: 'Arjun Menon',
    completedAt: '2026-09-19T17:10', completedBy: 'Arjun Menon',
  },
  {
    ref: 'DL-3015', customer: 'Lumen Projects', contact: 'Devika Nair',
    address: '2 MIDC Industrial Area', from: 'WH-CEN/Main-Storage/Rack-B',
    scheduledDate: '2026-09-03', carrier: 'DHL Express', status: 'Done',
    lines: dl([{ sku: 'CAB-CAT6-01', qty: 3, bin: 'Rack B' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-02T10:00', createdBy: 'Priya Patel',
    completedAt: '2026-09-03T11:30', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3016', customer: 'Printline Packaging', contact: 'Meera Joshi',
    address: '19 Industrial Estate Phase I', from: 'WH-CEN/Main-Storage/Bay-04',
    scheduledDate: '2026-08-24', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'LBL-406-01', qty: 18, bin: 'Bay 04' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-23T09:40', createdBy: 'Priya Patel',
    completedAt: '2026-08-24T13:40', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3017', customer: 'Pixel Print House', contact: 'Aakash Verma',
    address: '7 Riverside Design Park', from: 'WH-DSP/Packing-Area',
    scheduledDate: '2026-09-21', carrier: 'Internal Shuttle', status: 'Done',
    lines: dl([{ sku: 'LBL-406-01', qty: 8, bin: 'Packing Bench 2' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-09-20T16:20', createdBy: 'Priya Patel',
    completedAt: '2026-09-21T17:25', completedBy: 'Priya Patel',
  },
  {
    ref: 'DL-3018', customer: 'Kaveri Traders', contact: 'Naveen Iyer',
    address: '88 Sawmill Road', from: 'WH-CEN/Main-Storage/Heavy-Rack-A',
    scheduledDate: '2026-08-26', carrier: 'TCI Freight', status: 'Done',
    lines: dl([{ sku: 'COP-50M-01', qty: 4, bin: 'Heavy Rack A' }]),
    notes: 'Delivered and signed off.', createdAt: '2026-08-25T10:00', createdBy: 'Priya Patel',
    completedAt: '2026-08-26T15:00', completedBy: 'Priya Patel',
  },
];

const TRANSFERS: Transfer[] = [
  {
    ref: 'TR-2001',
    from: 'WH-CEN',
    to: 'WH-PRD/Production-Rack',
    lines: tl([{ sku: 'STL-ROD-12', qty: 100 }]),
    status: 'Draft',
    reason: 'Line-side replenishment for the fabrication order.',
    requestedBy: 'Priya Patel',
    createdAt: '2026-09-25T10:40',
  },
  {
    ref: 'TR-2002',
    from: 'WH-CEN/Main-Storage/Bay-04',
    to: 'WH-SEC/Main-Storage',
    lines: tl([{ sku: 'MOU-WLS-01', qty: 10 }]),
    status: 'Ready',
    reason: 'Top up the overflow yard ahead of the Monday service run.',
    requestedBy: 'Rahul Sharma',
    createdAt: '2026-09-25T14:05',
  },
  {
    ref: 'TR-2003',
    from: 'WH-CEN/Main-Storage/Bay-04',
    to: 'WH-DSP/Packing-Area',
    lines: tl([{ sku: 'LBL-406-01', qty: 5 }]),
    status: 'Draft',
    reason: 'Stage label stock for the weekly print run.',
    requestedBy: 'Priya Patel',
    createdAt: '2026-09-25T15:20',
  },
  {
    ref: 'TR-2004', from: 'WH-CEN/Main-Storage/Heavy-Rack-A', to: 'WH-SEC/Main-Storage',
    lines: tl([{ sku: 'COP-50M-01', qty: 2 }]), status: 'Done',
    reason: 'Relocation to the overflow yard.', requestedBy: 'Priya Patel',
    createdAt: '2026-08-31T16:10', completedAt: '2026-09-01T09:20', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2006', from: 'WH-CEN/Main-Storage/Rack-B', to: 'WH-SEC/Main-Storage',
    lines: tl([{ sku: 'SSD-SAM-1TB', qty: 6 }]), status: 'Done',
    reason: 'Relocation to the overflow yard.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-01T15:30', completedAt: '2026-09-02T11:10', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2007', from: 'WH-CEN/Main-Storage/Rack-B', to: 'WH-PRD/Assembly-Area',
    lines: tl([{ sku: 'RAM-KNG-16', qty: 8 }]), status: 'Done',
    reason: 'Kitted to the assembly line.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-03T16:00', completedAt: '2026-09-04T09:45', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2008', from: 'WH-CEN/Main-Storage/Bay-04', to: 'WH-DSP/Ready-to-Ship',
    lines: tl([{ sku: 'MON-DEL-24', qty: 1 }]), status: 'Done',
    reason: 'Stage on the outbound dock.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-19T17:40', completedAt: '2026-09-20T08:50', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2009', from: 'WH-CEN/Main-Storage/Rack-B', to: 'WH-SEC/Main-Storage',
    lines: tl([{ sku: 'SCN-IND-2D', qty: 3 }]), status: 'Done',
    reason: 'Top up the overflow yard.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-08T16:20', completedAt: '2026-09-09T10:20', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2010', from: 'WH-CEN/Main-Storage/Bay-04', to: 'WH-DSP/Ready-to-Ship',
    lines: tl([{ sku: 'CHR-ERG-01', qty: 2 }]), status: 'Done',
    reason: 'Stage on the outbound dock.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-16T15:30', completedAt: '2026-09-17T11:00', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2011', from: 'WH-CEN/Main-Storage/Bay-04', to: 'WH-PRD/Assembly-Area',
    lines: tl([{ sku: 'MOU-WLS-01', qty: 12 }]), status: 'Done',
    reason: 'Consumables for the assembly line.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-10T16:40', completedAt: '2026-09-11T09:40', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2012', from: 'WH-CEN/Main-Storage/Rack-B', to: 'WH-SEC/Main-Storage',
    lines: tl([{ sku: 'CAB-CAT6-01', qty: 2 }]), status: 'Done',
    reason: 'Relocation to the overflow yard.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-07T11:10', completedAt: '2026-09-08T15:15', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2013', from: 'WH-SEC/Main-Storage', to: 'WH-CEN/Main-Storage/Rack-B',
    lines: tl([{ sku: 'CAB-CAT6-01', qty: 1 }]), status: 'Done',
    reason: 'Pulled back for an urgent order.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-21T17:30', completedAt: '2026-09-22T08:35', completedBy: 'Priya Patel',
  },
  {
    ref: 'TR-2014', from: 'WH-CEN/Main-Storage/Bay-04', to: 'WH-DSP/Packing-Area',
    lines: tl([{ sku: 'LBL-406-01', qty: 4 }]), status: 'Done',
    reason: 'Weekly print run.', requestedBy: 'Priya Patel',
    createdAt: '2026-09-11T16:20', completedAt: '2026-09-12T08:45', completedBy: 'Priya Patel',
  },
];

const ADJUSTMENTS: Adjustment[] = [
  {
    ref: 'ADJ-4001',
    sku: 'STL-ROD-12',
    location: 'WH-PRD/Production-Rack',
    recorded: 0,
    counted: null,
    difference: null,
    reason: 'Damaged',
    notes: 'Production rack count. Enter the weighed quantity to raise the variance.',
    status: 'Draft',
    createdAt: '2026-09-25T17:05',
    createdBy: 'Priya Patel',
  },
  {
    ref: 'ADJ-4002',
    sku: 'MOU-WLS-01',
    location: 'WH-CEN/Main-Storage/Bay-04',
    recorded: 34,
    counted: 32,
    difference: -2,
    reason: 'Missing',
    notes: 'Two units short of the book position after the full bin count.',
    status: 'Pending Approval',
    countRef: 'CNT-5001',
    createdAt: '2026-09-26T08:05',
    createdBy: 'Priya Patel',
    submittedBy: 'Priya Patel',
  },
  {
    ref: 'ADJ-4003',
    sku: 'CHR-ERG-01',
    location: 'WH-CEN/Main-Storage/Bay-04',
    recorded: 23,
    counted: 22,
    difference: -1,
    reason: 'Damaged',
    notes: 'One chair frame cracked in transit. Scrapped on the count floor.',
    status: 'Posted',
    countRef: 'CNT-5003',
    createdAt: '2026-09-10T13:40',
    createdBy: 'Priya Patel',
    submittedBy: 'Priya Patel',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-10T15:20',
  },
  {
    ref: 'ADJ-4004',
    sku: 'SSD-SAM-1TB',
    location: 'WH-CEN/Main-Storage/Rack-B',
    recorded: 44,
    counted: 44,
    difference: 0,
    reason: 'Counting Error',
    notes: 'Recount matched the book position. No adjustment required — line rejected to keep the audit trail clean.',
    status: 'Rejected',
    countRef: 'CNT-5003',
    createdAt: '2026-09-10T14:05',
    createdBy: 'Priya Patel',
    submittedBy: 'Priya Patel',
    approvedBy: 'Rahul Sharma',
  },
  {
    ref: 'ADJ-4005',
    sku: 'SSD-SAM-1TB',
    location: 'WH-CEN/Main-Storage/Rack-B',
    recorded: 44,
    counted: 45,
    difference: 1,    reason: 'Counting Error',
    notes: 'One drive found in an unlabelled carton during a spot check.',
    status: 'Posted',
    createdAt: '2026-09-12T08:50',
    createdBy: 'Arjun Menon',
    submittedBy: 'Arjun Menon',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-12T09:30',
  },
  {
    ref: 'ADJ-4006',
    sku: 'SCN-IND-2D',
    location: 'WH-SEC/Main-Storage',
    recorded: 3,
    counted: 4,
    difference: 1,
    reason: 'Incorrect Entry',
    notes: 'Inbound receipt was short by one. Supplier credit raised.',
    status: 'Posted',
    createdAt: '2026-09-17T15:20',
    createdBy: 'Arjun Menon',
    submittedBy: 'Arjun Menon',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-17T16:45',
  },
  {
    ref: 'ADJ-4007',
    sku: 'MOU-WLS-01',
    location: 'WH-CEN/Main-Storage/Bay-04',
    recorded: 32,
    counted: 34,
    difference: 2,
    reason: 'Counting Error',
    notes: 'Two units found behind a racking beam.',
    status: 'Posted',
    createdAt: '2026-09-23T08:55',
    createdBy: 'Arjun Menon',
    submittedBy: 'Arjun Menon',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-23T09:25',
  },
  {
    ref: 'ADJ-4008',
    sku: 'CAB-CAT6-01',
    location: 'WH-SEC/Main-Storage',
    recorded: 6,
    counted: 4,
    difference: -2,
    reason: 'Damaged',
    notes: 'Outer wrap torn and water ingressed on two reels.',
    status: 'Posted',
    createdAt: '2026-09-16T10:10',
    createdBy: 'Arjun Menon',
    submittedBy: 'Arjun Menon',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-16T10:50',
  },
  {
    ref: 'ADJ-4009',
    sku: 'LBL-406-01',
    location: 'WH-CEN/Main-Storage/Bay-04',
    recorded: 32,
    counted: 27,
    difference: -5,
    reason: 'Missing',
    notes: 'Five reels unaccounted for at the monthly count. Investigation INV-221 opened.',
    status: 'Posted',
    createdAt: '2026-09-01T14:30',
    createdBy: 'Rahul Sharma',
    submittedBy: 'Rahul Sharma',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-01T16:00',
  },
  {
    ref: 'ADJ-4010',
    sku: 'COP-50M-01',
    location: 'WH-CEN/Main-Storage/Heavy-Rack-A',
    recorded: 15,
    counted: 14,
    difference: -1,
    reason: 'Expired',
    notes: 'One reel past its shelf life. Quarantined and written off.',
    status: 'Posted',
    createdAt: '2026-09-14T11:00',
    createdBy: 'Arjun Menon',
    submittedBy: 'Arjun Menon',
    approvedBy: 'Rahul Sharma',
    postedAt: '2026-09-14T11:40',
  },
];

const COUNTS: Count[] = [
  {
    ref: 'CNT-5001',
    warehouse: 'WH-CEN',
    location: 'WH-CEN/Main-Storage/Bay-04',
    category: '',
    assignedTo: 'Priya Patel',
    dueDate: '2026-09-27',
    status: 'In Progress',
    lines: [
      { id: lineId('CL'), sku: 'MOU-WLS-01', location: 'WH-CEN/Main-Storage/Bay-04', systemQty: 34, counted: 32, note: 'Two short against the book position.' },
      { id: lineId('CL'), sku: 'LBL-406-01', location: 'WH-CEN/Main-Storage/Bay-04', systemQty: 23, counted: 23, note: 'Matched.' },
      { id: lineId('CL'), sku: 'CHR-ERG-01', location: 'WH-CEN/Main-Storage/Bay-04', systemQty: 20, counted: 20, note: 'Matched.' },
      { id: lineId('CL'), sku: 'MON-DEL-24', location: 'WH-CEN/Main-Storage/Bay-04', systemQty: 4, counted: null, note: '' },
    ],
    notes: 'Monthly cycle count for Bay 04. Raise any variance for approval before posting.',
    createdAt: '2026-09-25T08:00',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'CNT-5002',
    warehouse: 'WH-SEC',
    location: 'WH-SEC/Main-Storage',
    category: '',
    assignedTo: 'Arjun Menon',
    dueDate: '2026-10-01',
    status: 'Scheduled',
    lines: [
      { id: lineId('CL'), sku: 'SSD-SAM-1TB', location: 'WH-SEC/Main-Storage', systemQty: 6, counted: null, note: '' },
      { id: lineId('CL'), sku: 'SCN-IND-2D', location: 'WH-SEC/Main-Storage', systemQty: 4, counted: null, note: '' },
      { id: lineId('CL'), sku: 'CAB-CAT6-01', location: 'WH-SEC/Main-Storage', systemQty: 3, counted: null, note: '' },
      { id: lineId('CL'), sku: 'COP-50M-01', location: 'WH-SEC/Main-Storage', systemQty: 2, counted: null, note: '' },
    ],
    notes: 'Quarterly count of the overflow yard.',
    createdAt: '2026-09-24T11:30',
    createdBy: 'Rahul Sharma',
  },
  {
    ref: 'CNT-5003',
    warehouse: 'WH-CEN',
    location: 'WH-CEN/Main-Storage',
    category: 'Furniture',
    assignedTo: 'Priya Patel',
    dueDate: '2026-09-10',
    status: 'Completed',
    lines: [
      { id: lineId('CL'), sku: 'CHR-ERG-01', location: 'WH-CEN/Main-Storage/Bay-04', systemQty: 23, counted: 22, note: 'One frame cracked in transit.' },
      { id: lineId('CL'), sku: 'SSD-SAM-1TB', location: 'WH-CEN/Main-Storage/Rack-B', systemQty: 44, counted: 44, note: 'Recount matched — no variance.' },
    ],
    notes: 'Spot count after the transit damage report.',
    createdAt: '2026-09-09T09:00',
    createdBy: 'Rahul Sharma',
    completedAt: '2026-09-10T14:30',
  },
];

/* ------------------------------------------------------------------- build */

export function buildSeed(): Database {
  const products: Product[] = PRODUCT_SEEDS.map((p) => ({ ...p, stock: {} }));
  const bySku = new Map(products.map((p) => [p.sku, p]));

  const history = new HistoryBuilder(bySku);
  for (const sku of Object.keys(HISTORY)) history.run(sku, HISTORY[sku]!);
  // Steel rods deliberately have no history: the demo starts at zero.
  bySku.get('STL-ROD-12')!.stock = {};

  const ledger = [...history.ledger].sort((a, b) => a.at.localeCompare(b.at));
  ledger.forEach((entry, idx) => {
    entry.id = `LG-${String(idx + 1).padStart(5, '0')}`;
  });

  // Open documents reserve stock. Reserved is derived from these lines only.
  for (const receipt of RECEIPTS) {
    for (const line of receipt.lines) {
      if (line.barcode === '') line.barcode = bySku.get(line.sku)?.barcode ?? '';
    }
  }

  return {
    version: SEED_VERSION,
    builtAt: `${TODAY}T06:00`,
    settings: {
      company: {
        name: 'StockSense Logistics',
        legalName: 'StockSense Logistics Private Limited',
        gstin: '27AABCS1429B1ZX',
        address: 'Survey 118, Logistics Park Road',
        city: 'Pune',
        country: 'India',
        timezone: 'Asia/Kolkata (IST)',
        currency: '₹',
        fiscalYearStart: '01-04',
      },
      preventNegativeStock: true,
      approvalRequired: true,
      approvalValueThreshold: 2500,
      approvalVariancePct: 2.5,
      defaultUom: 'Units',
      allowPartialDeliveries: false,
      notificationEmail: true,
      notificationInApp: true,
      lowStockDigest: true,
      sessionTimeoutHours: 12,
      theme: 'light',
      density: 'comfortable',
    },
    users: USERS,
    credentials: USERS.map((u) => ({ userId: u.id, ...hashPassword(PASSWORDS[u.id] ?? 'Demo@1234') })),
    categories: CATEGORIES,
    warehouses: WAREHOUSES,
    locations: LOCATIONS,
    products,
    receipts: RECEIPTS,
    deliveries: DELIVERIES,
    transfers: TRANSFERS,
    adjustments: ADJUSTMENTS,
    counts: COUNTS,
    ledger,
    events: [],
    readNotifications: [],
  };
}
